name:                h2048
version:             0.1.0.0
github:              "nodew/h2048"
license:             BSD3
author:              "Joe Wang"
maintainer:          "wangqiao11@hotmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/nodew/h2048#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- reactive-banana
- random
- lens

library:
  source-dirs: src
  exposed-modules:
  - H2048.Renderer
  - H2048.Types
  - H2048.Core
  - H2048.Game
  - Graphics.Gloss.Interface.FRP.ReactiveBanana

executables:
  h2048-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h2048

tests:
  h2048-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h2048
